@API_URL = http://localhost:3003/api/blogs

### List blogs
GET {{API_URL}}

### Add new blog
POST {{API_URL}}
Content-Type: application/json

{
    "title":"Full Stack Open 2020",
    "author":"Jonatandb",
    "url":"github.com/Jonatandb",
    "likes": 100
}

### Delete a blog
DELETE {{API_URL}}/5f90cb615691372444096dcc