@API_URL = http://localhost:3003/api/users

### List users
GET {{API_URL}}

### Add new user
POST {{API_URL}}
Content-Type: application/json

{
    "name":"Jonatandb",
    "username":"Jonatandb",
    "password": "123"
}