@API_URL = http://localhost:3003/api/blogs

### List blogs
GET {{API_URL}}

### Add new blog
POST {{API_URL}}
Content-Type: application/json

{
    "title":"Full Stack Open 2020",
    "author":"Jonatandb",
    "url":"github.com/Jonatandb",
    "likes": 100
}

### Delete a blog
DELETE {{API_URL}}/5f90d0cb0a305d1460e84f4c

### Update a blog
PUT {{API_URL}}/5f90d0e80a305d1460e84f4d
Content-Type: application/json

{
    "likes": 65461
}